# Generated by Django 4.2.1 on 2023-09-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(default='Descrição padrão', max_length=200, verbose_name='Descricao')),
                ('query', models.CharField(max_length=5000, unique=True, verbose_name='Query')),
                ('modulo', models.ForeignKey(blank=True, db_column='modulo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicacao.modulo', verbose_name='Modulo')),
                ('sistema', models.ForeignKey(db_column='sistema_id', on_delete=django.db.models.deletion.PROTECT, to='aplicacao.sistema', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='modulo',
            name='sistema',
            field=models.ForeignKey(db_column='sistema_id', on_delete=django.db.models.deletion.PROTECT, to='aplicacao.sistema', verbose_name='Sistema'),
        ),
    ]
