# Generated by Django 4.2.5 on 2023-09-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_alter_query_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True, verbose_name='Nome')),
                ('sistema', models.ForeignKey(db_column='sistema_id', on_delete=django.db.models.deletion.PROTECT, to='aplicacao.sistema', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulo',
                'ordering': ['nome'],
            },
        ),
    ]
