# Generated by Django 4.2.5 on 2023-09-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='modulo',
            field=models.ForeignKey(blank=True, db_column='modulo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicacao.modulo', verbose_name='Modulo'),
        ),
    ]
